version: "3.9"

services:

  api:
    build:
      context: ./backend
    container_name: wms_api
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - wms_network

  worker:
    build:
      context: ./backend
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - wms_network

  redis:
    image: redis:7-alpine
    container_name: wms_redis
    restart: always
    networks:
      - wms_network

  db:
    image: postgres:15-alpine
    container_name: wms_db
    restart: always
    environment:
      POSTGRES_DB: wms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wms_network

networks:
  wms_network:

volumes:
  postgres_data: